name: Release and publish snowflakes

on:
  push:
    branches:
      - main

# jobs:
#   release:
#     permissions:
#       contents: write
#       issues: write
#       pull-requests: write
#       packages: write
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#           token: ${{ secrets.CI_GITHUB_TOKEN }}
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 22.12.0
#       - run: npm ci
#       - run: npx semantic-release
#         env:
#           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}